# Generated by Django 5.2.8 on 2025-11-13 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("heading", models.CharField(default="About Me", max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("highlight_quote", models.TextField(blank=True)),
                ("highlight_caption", models.CharField(blank=True, max_length=200)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
            ],
            options={
                "verbose_name": "About section",
                "verbose_name_plural": "About section",
            },
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "text",
                    models.CharField(
                        default="© Portfolio. Crafted with passion.", max_length=255
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Footer",
                "verbose_name_plural": "Footer",
            },
        ),
        migrations.CreateModel(
            name="NavigationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=80)),
                (
                    "target",
                    models.CharField(
                        help_text="Section id (without #) or full URL.", max_length=150
                    ),
                ),
                ("is_external", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Navigation link",
                "verbose_name_plural": "Navigation links",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                (
                    "gradient_start",
                    models.CharField(
                        default="#ff8f2c",
                        help_text="Starting color (hex or hsl).",
                        max_length=20,
                    ),
                ),
                (
                    "gradient_end",
                    models.CharField(
                        default="#ffd166",
                        help_text="Ending color (hex or hsl).",
                        max_length=20,
                    ),
                ),
                ("live_url", models.URLField(blank=True)),
                ("code_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume_type",
                    models.CharField(
                        choices=[
                            ("professional", "Professional resume"),
                            ("ats", "ATS friendly resume"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("file", models.FileField(upload_to="resumes/")),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resumes",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand_name",
                    models.CharField(default="ananthu.online", max_length=150),
                ),
                ("brand_subtitle", models.CharField(blank=True, max_length=150)),
                (
                    "hero_heading",
                    models.CharField(default="ANANTHU S KUMAR", max_length=200),
                ),
                ("hero_highlight", models.CharField(blank=True, max_length=200)),
                ("hero_subheading", models.CharField(blank=True, max_length=200)),
                ("hero_description", models.TextField(blank=True)),
                (
                    "primary_cta_label",
                    models.CharField(default="Hire Me", max_length=80),
                ),
                (
                    "primary_cta_action",
                    models.CharField(
                        choices=[
                            ("scroll", "Scroll to section"),
                            ("url", "Open URL"),
                            ("modal", "Open modal"),
                        ],
                        default="modal",
                        max_length=10,
                    ),
                ),
                (
                    "primary_cta_target",
                    models.CharField(
                        blank=True,
                        help_text="Section id (without #), URL, or modal key depending on action.",
                        max_length=120,
                    ),
                ),
                (
                    "secondary_cta_label",
                    models.CharField(default="View Work", max_length=80),
                ),
                (
                    "secondary_cta_action",
                    models.CharField(
                        choices=[
                            ("scroll", "Scroll to section"),
                            ("url", "Open URL"),
                            ("modal", "Open modal"),
                        ],
                        default="scroll",
                        max_length=10,
                    ),
                ),
                (
                    "secondary_cta_target",
                    models.CharField(
                        blank=True,
                        help_text="Section id (without #) or URL.",
                        max_length=120,
                    ),
                ),
                ("whatsapp_link", models.URLField(blank=True)),
                ("calendly_link", models.URLField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("highlight", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Skill category",
                "verbose_name_plural": "Skill categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=80)),
                ("url", models.URLField()),
                (
                    "icon_name",
                    models.CharField(
                        help_text="Name of the Lucide icon (e.g. 'github', 'linkedin').",
                        max_length=80,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Social link",
                "verbose_name_plural": "Social links",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_name", models.CharField(max_length=120)),
                ("author_role", models.CharField(blank=True, max_length=120)),
                ("quote", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AboutHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.CharField(max_length=255)),
                (
                    "icon_name",
                    models.CharField(
                        help_text="Name of the Lucide icon to render (e.g. 'code-2', 'zap').",
                        max_length=80,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="content.aboutsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "About highlight",
                "verbose_name_plural": "About highlights",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech",
                        to="content.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project technology",
                "verbose_name_plural": "Project technologies",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SkillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="skills/")),
                ("logo_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="content.skillcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["order"],
            },
        ),
    ]
