# Generated by Django 5.2.8 on 2025-11-13 11:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="file",
            field=models.FileField(
                upload_to="resumes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="primary_cta_target",
            field=models.CharField(
                blank=True,
                help_text="Section id (without #), URL or modal key depending on action.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="secondary_cta_target",
            field=models.CharField(
                blank=True,
                help_text="Section id (without #) or URL depending on action.",
                max_length=120,
            ),
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="content.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project image",
                "verbose_name_plural": "Project images",
            },
        ),
    ]
